name: docs

on:
  push:
    branches:
      - master
      - releases/*

  pull_request:
    paths:
      - "pystiche/**"
      - "docs/**"
      - "examples/**"
      - "tox.ini"
      - "requirements-dev.txt"
      - ".github/workflows/docs.yml"
      - "setup.cfg"
      - "pyproject.toml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install latex requirements
        run: |
          sudo apt update -y
          sudo apt install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

      - name: Check config
        run: kpsewhich -a texmf.cnf

      - name: Display config
        run: nl /usr/share/texlive/texmf-dist/web2c/texmf.cnf

      - name: Increase memory
        run: |
          sudo sed -i "s/main_memory = \([0-9]\+\).*/main_memory = \10/" /usr/share/texlive/texmf-dist/web2c/texmf.cnf
          nl /usr/share/texlive/texmf-dist/web2c/texmf.cnf | grep main_memory

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Upgrade or install additional system packages
        run: pip install --upgrade pip setuptools virtualenv wheel

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Create environment
        run: tox -e docs --notest

      - name: Build documentation
        run: tox -e docs

#      - name: Upload html build
#        uses: actions/upload-artifact@v2
#        with:
#          name: html
#          path: docs/build/html
#
#      - name: Upload latex build
#        uses: actions/upload-artifact@v2
#        with:
#          name: latex
#          path: docs/build/latex/pystiche.pdf
